
  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;


import dao.DAOFactory;
import dao.DAOGenerico;
import dao.PessoaDAO;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class frmPrincipal extends javax.swing.JFrame {

PessoaDAO pessoaDAO = DAOFactory.criarPessoaDAO();

    private int nextId = 1;
    
    public frmPrincipal() {
        initComponents();
        atualizarNextId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Incluir = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Remover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        Incluir.setText("Incluir");
        Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncluirActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Remover.setText("Remover");
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Data de Nascimento"
            }
        ));
        Tabela.setColumnSelectionAllowed(true);
        Tabela.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                TabelaComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);
        Tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(Incluir)
                .addGap(41, 41, 41)
                .addComponent(Editar)
                .addGap(34, 34, 34)
                .addComponent(Remover)
                .addGap(47, 47, 47)
                .addComponent(Sair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Incluir)
                    .addComponent(Editar)
                    .addComponent(Remover)
                    .addComponent(Sair))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncluirActionPerformed
           String nome = JOptionPane.showInputDialog(this, "Digite o nome: ");
           String dataNascimento = JOptionPane.showInputDialog(this, "Digite a data de nascimento: ");
           
           if(nome != null && dataNascimento != null && !nome.trim().isEmpty() && !dataNascimento.trim().isEmpty()){
                  DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
                  model.addRow( new Object[]{nextId, nome, dataNascimento}
                  
                  );
                  nextId++;
           }else{
               JOptionPane.showMessageDialog(this, "Nome e Data de nascimento não pode estar vazio.");
           }
    }//GEN-LAST:event_IncluirActionPerformed

  
    private void TabelaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_TabelaComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaComponentAdded

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        int selectedRow = Tabela.getSelectedRow();
         if(selectedRow >= 0){
             String nome = JOptionPane.showInputDialog(this, "Digite o novo nome: ", Tabela.getValueAt(selectedRow, 1));
             String dataNascimento = JOptionPane.showInputDialog(this, "Digite a nova data de nascimento: ", Tabela.getValueAt(selectedRow, 2));
             
             if(nome != null && dataNascimento != null){
                 Tabela.setValueAt(nome, selectedRow, 1);
                 Tabela.setValueAt(dataNascimento, selectedRow, 2);
             }
         }else{
             JOptionPane.showMessageDialog(this,"Selecione uma linha para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
         }
    }//GEN-LAST:event_EditarActionPerformed

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        int selectedRow = Tabela.getSelectedRow();
            if(selectedRow >= 0){
                DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
                model.removeRow(selectedRow);
            }else{
                JOptionPane.showMessageDialog(this,"Selecione uma linha para remover.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_RemoverActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void reajustarIDs(){
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
            for(int i = 0; i < model.getRowCount(); i++){
                model.setValueAt(i + 1, i, 0); 
            }
            atualizarNextId();
    }
    
    private void atualizarNextId(){
        DefaultTableModel model = (DefaultTableModel)Tabela.getModel();
            if(model.getRowCount() > 0){
                int maxId = 0;
                for(int i = 0; i < model.getRowCount(); i++){
                    Object value = model.getValueAt(i, 0);
                    if(value != null && value instanceof Integer){
                        int id = (Integer) value;
                       if(id > maxId){
                            maxId = id;
                        }
                    }
                }    
                nextId = maxId +1;
            }else{
                nextId = 1;
            } 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JButton Incluir;
    private javax.swing.JButton Remover;
    private javax.swing.JButton Sair;
    private javax.swing.JTable Tabela;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
